// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZfybiOOpbNOQzJWypweFR7ueUKULUPr8',
    appId: '1:844312883246:web:2688303940695c7d466fbf',
    messagingSenderId: '844312883246',
    projectId: 'rescue-notice-app',
    authDomain: 'rescue-notice-app.firebaseapp.com',
    storageBucket: 'rescue-notice-app.appspot.com',
    measurementId: 'G-THLK6J3CQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD19hlQlWMurkbWCEZF4uV1nvb4miUDuZo',
    appId: '1:844312883246:android:a57c33a0d330e11f466fbf',
    messagingSenderId: '844312883246',
    projectId: 'rescue-notice-app',
    storageBucket: 'rescue-notice-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUKynRIYHuVa6hqHPaF_vVfk2PopjESiQ',
    appId: '1:844312883246:ios:b75046e5ab4f18d7466fbf',
    messagingSenderId: '844312883246',
    projectId: 'rescue-notice-app',
    storageBucket: 'rescue-notice-app.appspot.com',
    iosClientId: '844312883246-dh5thr14fd257csg4peo1vi0fg6ieode.apps.googleusercontent.com',
    iosBundleId: 'com.example.thecover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUKynRIYHuVa6hqHPaF_vVfk2PopjESiQ',
    appId: '1:844312883246:ios:615c2f3ae2b8d152466fbf',
    messagingSenderId: '844312883246',
    projectId: 'rescue-notice-app',
    storageBucket: 'rescue-notice-app.appspot.com',
    iosClientId: '844312883246-vk75m57ta65j4vrbiedorfvgc4sn2lmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.thecover.RunnerTests',
  );
}
